#!/usr/bin/env ruby
# frozen_string_literal: true

require 'scss_lint_auto_correct'
require 'scss_lint_auto_correct/logger'
require 'scss_lint_auto_correct/cli'

logger = SCSSLintAutoCorrect::Logger.new(STDOUT)
SCSSLintAutoCorrect::CLI.new(logger).run(ARGV)
exit
