#!/usr/bin/env ruby
# frozen_string_literal: true

require 'scss_lint_auto_correct'
require 'scss_lint_auto_correct/scss_lint_bypass'
require 'scss_lint_auto_correct/cli'
require 'scss_lint_auto_correct/logger'

opts = {
  color: !!(STDOUT.respond_to?(:tty?) && STDOUT.tty?)
}

SCSSLintAutoCorrect::SCSSLintBypass.new.run(opts) do |result, exit_status|
  logger = SCSSLintAutoCorrect::Logger.new(STDOUT)
  SCSSLintAutoCorrect::CLI.new(logger).run(result)
  exit exit_status
end
